### ISSUE TITLE
Getting a null ref when making calls

### ISSUE THREAD

**Issue by frostebite** [Scordo/TS3QueryLib.Net.Core#7]
Regularly getting the following error when making calls. Not sure why. @Scordo 

`Error: Object reference not set to an instance of an object.,    at System.Net.Sockets.SocketTaskExtensions.SendAsync(Socket socket, ArraySegment`1 buffer, SocketFlags socketFlags)
   at TS3QueryLib.Net.Core.QueryClient.<SendAsync>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at TS3QueryLib.Net.Core.QueryClient.<SendAsync>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TS3QueryLib.Net.Core.AsyncHelper.RunSync[TResult](Func`1 func)
   at TS3QueryLib.Net.Core.QueryClient.Send(String messageToSend)
   at TS3QueryLib.Net.Core.QueryClient.TS3QueryLib.Net.Core.ICommandExecutor.Execute(ICommand command)
   at TS3QueryLib.Net.Core.Common.Commands.ExecutableCommand`1.Execute(ICommandExecutor executor)
   at UKSFWebsite.Api.Services.TeamspeakQueryServiceSingleton.Connect() in D:\home\site\repository\UKSFWebsite.api\Services\TeamspeakQueryServiceSingleton.cs:line 43
   at lambda_method(Closure , ServiceProvider )
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()`

**Comment by Scordo** [comment]
Seems like it is during Connect? And you are using the Sync-Version? Which version are you using? Seems like you are using an older version?!

Can you show me the content of "UKSFWebsite.Api.Services.TeamspeakQueryServiceSingleton.Connect()" an tell me wich is line "43"?

**Comment by frostebite** [comment]
My code has changed a little from this. I _think_ the error is related to trying to disconnect not in the correct order.

But it seems many of the errors are not being caught by my try catch blocks. Is there a reason for this?

I'm using the latest nuget, is that very old?

**Comment by frostebite** [comment]
I regularly get 
http://prntscr.com/hjo5am

**Comment by Scordo** [comment]
The reason you're code is not catching all exceptions is, that there is a Task in the Background running from the beginning of the "Connect" call which is Reading on the socket and pushing read lines into a queue. This queue is used by the Execute() method of the command to get the results. If an exceptions is thrown within this loop (task) you'll not be able to catch it. Are you sure you are using versio 0.5? The Stacktrace seems to be from an older version.

**Comment by frostebite** [comment]
http://prntscr.com/hjs6mw

seems to be the latest.

**Comment by frostebite** [comment]
Currently I'm still getting occasionally failures that I'm totally unsure what makes them occur. And am not able to repro.

**Comment by frostebite** [comment]
could you not wrap the background task in a try catch and communicate back to the main thread with the exception that was caught. Then throw from the main thread?

**Comment by Scordo** [comment]
You're using version 0.3. This is not the latest version. Verison 0.3. was using another approach of socket communication which had problems. Please use version 0.5:

https://www.nuget.org/packages/TS3QueryLib.Net.Core/0.5.0-alpha

**Comment by frostebite** [comment]
Have updated thanks. Seems to be a bit more consistent however still getting the occasional failure :/

More concerningly. I'm occasionally managing to crash the teamspeak server being querried x.D

**Comment by frostebite** [comment]
What is the proper disconnection flow?
Right now to connect I do
`
            _client = new QueryClient("XX", 10011);
            connection = _client.Connect();
            loginResponse = new LoginCommand("XX", "XX").Execute(_client);
            portResponse = new UseCommand(9987).Execute(_client);`

and too disconnect I

`new QuitCommand().Execute(_client);
_client.Disconnect();
_client=null;`

**Comment by Scordo** [comment]
The Quitcomand should be enough.

**Comment by frostebite** [comment]
Thanks. This helps. Still get the occasional failed call. But that's fine.
